/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.skinny.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Skinny service. Represents a row in the &quot;Skinny_Skinny&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.skinny.model.impl.SkinnyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.skinny.model.impl.SkinnyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Skinny
 * @see com.liferay.skinny.model.impl.SkinnyImpl
 * @see com.liferay.skinny.model.impl.SkinnyModelImpl
 * @generated
 */
@ProviderType
public interface SkinnyModel extends BaseModel<Skinny> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a skinny model instance should use the {@link Skinny} interface instead.
	 */

	/**
	 * Returns the primary key of this skinny.
	 *
	 * @return the primary key of this skinny
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this skinny.
	 *
	 * @param primaryKey the primary key of this skinny
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dummy ID of this skinny.
	 *
	 * @return the dummy ID of this skinny
	 */
	public long getDummyId();

	/**
	 * Sets the dummy ID of this skinny.
	 *
	 * @param dummyId the dummy ID of this skinny
	 */
	public void setDummyId(long dummyId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Skinny skinny);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Skinny> toCacheModel();

	@Override
	public Skinny toEscapedModel();

	@Override
	public Skinny toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}